/* eslint-disable @next/next/no-img-element */
import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import Link from "next/link";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Audio Share</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {sessionData ? (
        <>
          <button
            className="rounded-md bg-slate-600 p-3 text-white"
            onClick={() => void signOut()}
          >
            Log Out
          </button>
          <Link href="/account">Account</Link>
        </>
      ) : (
        <button
          className="rounded-md bg-slate-600 p-3 text-white"
          onClick={() => void signIn()}
        >
          Log In
        </button>
      )}
    </>
  );
};

export default Home;
