/* eslint-disable @next/next/no-img-element */
import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "./components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Navbar />
      <Head>
        <title>Audio Share</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
};

export default Home;
